### ISSUE TITLE
install instruction error: celeryd

### ISSUE THREAD

**Issue by ferriswheel** [haystack/mailx#1]
hello Anant,

this section of the install instructions fails

   ## running in development mode ##
   # start celeryd
   python manage.py celeryd

with this response

$ python manage.py celeryd
   Unknown command: 'celeryd'
  Type 'manage.py help' for usage.

using python 2.7, pip 1.5.6, django 1.6.5, celery 3.1.12, django-celery 3.1.10

is mailx ready for testing or waitng for further development?

tia

regards 
john

**Comment by amyxzhang** [comment]
We're still doing further development (currently not using celery but the installation docs are out of date) but many parts are ready for testing.
