### ISSUE TITLE
Fix encoding/decoding issues comprehensively

### ISSUE THREAD

**Issue by amyxzhang** [haystack/mailx#18]
Current issues:

MySQL machine only supports 3-byte unicode and not 4-byte. What to do? Can't store as unicode but don't want to convert to ascii (lots unreadable). Convert to utf-8 ok (check mysql)?

try to do "unicode sandwich" everywhere.

read in charset encoding of email. Output utf-8 and check to make sure it is (not unicode) and looks ok.

**Comment by karger** [comment]
Switch to postures? 

<div>-------- Original message --------</div><div>From: Amy Zhang <notifications@github.com> </div><div>Date:05/14/2015  6:49 PM  (GMT-05:00) </div><div>To: haystack/mailx <mailx@noreply.github.com> </div><div>Cc:  </div><div>Subject: [mailx] Fix encoding/decoding issues comprehensively (#18) </div><div>
</div>Current issues:

MySQL machine only supports 3-byte unicode and not 4-byte. What to do? Can't store as unicode but don't want to convert to ascii (lots unreadable). Convert to utf-8 ok (check mysql)?

try to do "unicode sandwich" everywhere.

read in charset encoding of email. Output utf-8 and check to make sure it is (not unicode) and looks ok.

**Comment by amyxzhang** [comment]
Closing this since we haven't had problems with this in a long time.
